---
title: "Labor Force"
author: "Shelby Level"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r reading-laborforce-data, eval=FALSE}
library(tidyverse)

list.files(
  path = "data/labor force cty/",
  pattern = '\\.xlsx', 
  full.names = TRUE
  ) -> filenames 

purrr::map_df(
  filenames, 
  readxl::read_excel, 
  .id = 'laucnty'
  ) -> df

df[, 1:11] -> df2
df2$...6 = NULL 

df[6:106450, 1:11] %>%
  rename(
    file = laucnty, 
    laus.code = `Labor Force Data by County, 2000 Annual Averages`,
    state.fips = ...2, 
    county.fips = ...3,
    name = ...4,
    year = ...5,
    labor.force = ...7,
    employed = ...8,
    unemployed = ...9,
    unemployment.rate = ...10
    ) -> lf

lf$...6 = NULL
lf %>%
  filter(year != 'Year') -> labor_force

save(labor_force, file = "data/labor force cty/labor_force.rdata")
```

```{r}
load("data/labor force cty/labor_force.rdata")

labor_force %>% 
  filter(state.fips == 39) %>%
  mutate(county.fips = as.numeric(county.fips)) -> ohio

ohio %>%
  mutate(county.fips = as.numeric(county.fips)) %>%
  mutate(county.type = case_when(ohio$county.fips == 39003 | ohio$county.fips == 39003 | ohio$county.fips == 39017 | ohio$county.fips == 39035 | ohio$county.fips == 39049 | ohio$county.fips == 39061 | ohio$county.fips == 39093 | ohio$county.fips == 39095 | ohio$county.fips == 39099 | ohio$county.fips == 39113 | ohio$county.fips == 39139 | ohio$county.fips == 39151 | ohio$county.fips == 39153 ~ "Metropolitan") -> ohio
         

ohio$county.type[ohio$county.fips == c(3, 17, 35, 49, 61, 93, 95, 99, 113, 1, 151, 153)] = "Metropolitan" 

factor(ohio$county.type) -> ohio$county.type


Adams
Ashtabula
Athens
Belmont
Brown
Carroll
Clermont
Columbiana
Coshocton
Gallia
Guernsey
Harrison
Highland
Hocking
Holmes
Jackson
Jefferson
Lawrence
Meigs
Monroe
Morgan
Muskingum
Noble
Perry
Pike
Ross
Scioto
Trumbull
Tuscarawas
Vinton
Washington

```

